
package Interfaces;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Andy
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        this.setLocationRelativeTo(null);//frame al centro
        jDesktopPane1.setBorder(new fondoAcceso());
        this.setExtendedState(Menu.NORMAL);
        lblAccesoDenegado.setVisible(false);
        
    }
        public void ingresar(){
        Conexion cc= new Conexion();
        Connection cn=cc.conectar();
        String sql="";
        sql="SELECT * FROM public.USUARIOS";
        try {
            Statement psd=cn.createStatement();
            ResultSet rs= psd.executeQuery(sql);
            while(rs.next()){
               if(txtUsuario.getText().equals(rs.getString("usucodigo")) && Encriptacion.Encriptar(txtClave.getText()).equals(rs.getString("usuclave"))){
                   if(rs.getString("usuperfil").equals("administrador")){
                    Menu me= new Menu();
                    me.setExtendedState(MAXIMIZED_BOTH);
                    me.setVisible(true);
                    dispose();
                   }else if(rs.getString("usuperfil").equals("secretaria")){
                    Menu me= new Menu();
                    me.setExtendedState(MAXIMIZED_BOTH);
                    me.setVisible(true);
                    dispose();
                   }
                    lblAccesoDenegado.setVisible(false); 
               }else{
                   lblAccesoDenegado.setVisible(true);
               }
            }
            } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Error de Verificacion de Usuario "+ex);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        lblAccesoDenegado = new javax.swing.JLabel();
        jbtIngreso = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso");

        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Usuario:");
        jLabel1.setBounds(30, 80, 50, 20);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Constraseña:");
        jLabel2.setBounds(30, 120, 80, 20);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtUsuario.setBounds(120, 80, 120, 26);
        jDesktopPane1.add(txtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtClave.setBounds(120, 120, 120, 26);
        jDesktopPane1.add(txtClave, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblAccesoDenegado.setForeground(new java.awt.Color(255, 0, 0));
        lblAccesoDenegado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccesoDenegado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lblAccesoDenegado.png"))); // NOI18N
        lblAccesoDenegado.setText("Acceso Denegado");
        lblAccesoDenegado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblAccesoDenegado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAccesoDenegado.setBounds(30, 170, 220, 110);
        jDesktopPane1.add(lblAccesoDenegado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbtIngreso.setText("Ingresar");
        jbtIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIngresoActionPerformed(evt);
            }
        });
        jbtIngreso.setBounds(270, 80, 80, 29);
        jDesktopPane1.add(jbtIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(270, 120, 80, 29);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

private void jbtIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIngresoActionPerformed
ingresar();// TODO add your handling code here:
}//GEN-LAST:event_jbtIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtIngreso;
    private javax.swing.JLabel lblAccesoDenegado;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
